{
 "title": "EventServiceDashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Throughput",
   "type": "timeseries",
   "description": "Число запросов в секунду (шаг минута)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    http_server_request_duration_seconds_count{\r\n      job=\"events-service\",\r\n      http_route!=\"/metrics\"\r\n    }[1m]\r\n  )\r\n)",
     "legendFormat": "Requests per sec"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "stat",
   "description": "Число запросов прямо сейчас",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  http_server_active_requests{\r\n    job=\"events-service\",\r\n    http_route!=\"/metrics\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(\r\n    rate(\r\n      http_server_request_duration_seconds_count{\r\n        job=\"events-service\",\r\n        http_route!=\"/metrics\",\r\n        http_response_status_code=~\"5..\"\r\n      }[5m]\r\n    )\r\n  )\r\n  or vector(0)\r\n)\r\n/\r\nsum(\r\n  rate(\r\n    http_server_request_duration_seconds_count{\r\n      job=\"events-service\",\r\n      http_route!=\"/metrics\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "Errors%"
    },
    {
     "expr": "100 *\r\n(\r\n  sum(\r\n    rate(\r\n      http_server_request_duration_seconds_count{\r\n        job=\"events-service\",\r\n        http_route!=\"/metrics\",\r\n        http_response_status_code=~\"4..\"\r\n      }[5m]\r\n    )\r\n  )\r\n  or vector(0)\r\n)\r\n/\r\nsum(\r\n  rate(\r\n    http_server_request_duration_seconds_count{\r\n      job=\"events-service\",\r\n      http_route!=\"/metrics\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "Bad requests%"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum(\r\n    rate(\r\n      http_server_request_duration_seconds_count{\r\n        job=\"events-service\",\r\n        http_route!=\"/metrics\",\r\n        http_response_status_code=~\"5..\"\r\n      }[5m]\r\n    )\r\n  )\r\n  or vector(0)\r\n)\r\n/\r\nsum(\r\n  rate(\r\n    http_server_request_duration_seconds_count{\r\n      job=\"events-service\",\r\n      http_route!=\"/metrics\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "Errors%"
    },
    {
     "expr": "100 *\r\n(\r\n  sum(\r\n    rate(\r\n      http_server_request_duration_seconds_count{\r\n        job=\"events-service\",\r\n        http_route!=\"/metrics\",\r\n        http_response_status_code=~\"4..\"\r\n      }[5m]\r\n    )\r\n  )\r\n  or vector(0)\r\n)\r\n/\r\nsum(\r\n  rate(\r\n    http_server_request_duration_seconds_count{\r\n      job=\"events-service\",\r\n      http_route!=\"/metrics\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "Bad requests%"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le) (\r\n    rate(\r\n      http_server_request_duration_seconds_bucket{\r\n        job=\"events-service\",\r\n        http_route!=\"/metrics\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket{job=\"events-service\", http_route!=\"/metrics\"}[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_request_duration_seconds_bucket{job=\"events-service\", http_route!=\"/metrics\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}